name: tetrix_cli
description: A CLI for creating Flutter projects with custom setup.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  args: ^2.5.0
  mason: ^0.1.0-dev.56
  path: ^1.9.1
  yaml: ^3.1.2
  yaml_edit: ^2.2.1
  recase: ^4.0.0

dev_dependencies:
  very_good_analysis: ^5.0.0

executables:
  tetrix_cli: